/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.KhachHangBUS;
import DAO.KhachHangDAO;
import DAO.MySQLConnect;
import DTO.KhachHangDTO;
import GUISupport.TableDark;
import GUISupport.jpanelGradient;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.net.Inet4Address;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class KhachHangGUI extends javax.swing.JFrame {

    private ArrayList<KhachHangDTO> dstmp = new ArrayList<KhachHangDTO>();
    DefaultTableModel model = new DefaultTableModel();
    private KhachHangBUS khbs = new KhachHangBUS();
    private Object tmpCombox;
    private String getItem;
    private String getItemFilter = null;

    /**
     * Creates new form KhachHangGUI
     */
    public KhachHangGUI() {
        initComponents();
        CreateHeader();
        list();

// mặc định là chọn lấy cái giới tính nam 
        getItem = (String) ComboxGender.getModel().getSelectedItem();

    }

    public void CreateHeader() {
        Vector header = new Vector();
        header.add("CustomerID");
        header.add("CutomerLast");
        header.add("CustomerName");
        header.add("CustomerGender");
        header.add("CustomerBirth");
        header.add("CustomerAddress");
        header.add("CustomerTel");
        if (model.getRowCount() == 0) {
            model = new DefaultTableModel(header, 0);
        }
        tbl.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new jpanelGradient();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextHo = new javax.swing.JTextField();
        TextTen = new javax.swing.JTextField();
        TextSDT = new javax.swing.JTextField();
        ComboxGender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TextMa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TextAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TextBirth = new javax.swing.JTextField();
        BtnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        BtnDel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new TableDark();
        jLabel10 = new javax.swing.JLabel();
        ComboFilter = new javax.swing.JComboBox<>();
        TextFliter = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TextYearFrom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TextYearTo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BtnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnEdit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Họ ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Tên");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Giới Tính");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Số Điện Thoại");

        TextHo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        TextTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        TextSDT.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        ComboxGender.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ComboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        ComboxGender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboxGenderItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Mã khách hàng");

        TextMa.setEditable(false);
        TextMa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setText("Địa Chỉ");

        TextAddress.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAddressActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setText("Ngày Sinh ( dd-MM-yyyy ) ");

        TextBirth.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextBirth.setToolTipText("");

        BtnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEdit.setText("Sửa");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        BtnDel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDel.setText("Xóa");
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Xem danh sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextTen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextHo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboxGender, 0, 512, Short.MAX_VALUE)
                    .addComponent(TextMa)
                    .addComponent(TextBirth)
                    .addComponent(TextSDT)
                    .addComponent(TextAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BtnDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(BtnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Giới Tính");

        ComboFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không", "Nam", "Nữ" }));
        ComboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFilterActionPerformed(evt);
            }
        });

        TextFliter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextFliter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFliterActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Năm sinh");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Từ");

        TextYearFrom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Đến");

        TextYearTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextYearTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextYearToActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Tìm kiếm");

        BtnSearch.setText("Tìm Kiếm");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFliter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(ComboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(TextYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(TextYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSearch)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ComboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(TextYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TextYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(BtnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Quản Lý Khách Hàng");

        BtnEdit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEdit1.setText("Quay lại menu");
        BtnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEdit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEdit1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BtnEdit1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEdit1ActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(this, "Quay lại menu?", "Xác nhận quay lại", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            MENU menu = new MENU();
            menu.setVisible(true);
            closeFrame(this);
        }
    }//GEN-LAST:event_BtnEdit1ActionPerformed

    private void closeFrame(JFrame frame) {
        WindowEvent closeWindow = new WindowEvent(frame, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        String searchString = TextFliter.getText();
        ArrayList<KhachHangDTO> res;
        ArrayList<KhachHangDTO> data = khbs.getList();
        res = Search(searchString, data);

        if (res.size() != 0) {
            ShowModel(model, res);
        }
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void TextYearToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextYearToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextYearToActionPerformed

    private void TextFliterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFliterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFliterActionPerformed

    private void ComboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFilterActionPerformed
        if (ComboFilter.getModel().getSelectedItem().equals("Không")) {
            getItemFilter = null;
        } else {
            getItemFilter = (String) ComboFilter.getModel().getSelectedItem();
        }
    }//GEN-LAST:event_ComboFilterActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int i = tbl.getSelectedRow();
        System.out.println(i);
        TextMa.setText((String) tbl.getModel().getValueAt(i, 0));
        TextHo.setText((String) tbl.getModel().getValueAt(i, 1));
        TextTen.setText((String) tbl.getModel().getValueAt(i, 2));
        getItem = (String) tbl.getModel().getValueAt(i, 3);
        ComboxGender.getModel().setSelectedItem(getItem);
        TextBirth.setText((String) tbl.getModel().getValueAt(i, 4));
        TextAddress.setText((String) tbl.getModel().getValueAt(i, 5));
        TextSDT.setText((String) tbl.getModel().getValueAt(i, 6));
    }//GEN-LAST:event_tblMouseClicked

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
        khbs.delete(TextMa.getText());
        ShowModel(model, khbs.getList());
    }//GEN-LAST:event_BtnDelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        KhachHangDAO dsdao = new KhachHangDAO();
        ArrayList<KhachHangDTO> dstmp = dsdao.list();
        String IDTMP = "KH";
        KhachHangDTO khdto;
        if (dstmp == null) {
            System.out.println("Khong co du lieu trong bang khach hang");
            String MaKhachHang = IDTMP + "000";
            String Ho = TextHo.getText();
            String Ten = TextTen.getText();
            String sdt = TextSDT.getText();
            String address = TextAddress.getText();
            String birth = TextBirth.getText();
            khdto = new KhachHangDTO(MaKhachHang, Ho, Ten, getItem, birth, address, sdt);
        } else {
            KhachHangDTO tmp = dstmp.get(dstmp.size() - 1);
            String tmpMa = tmp.getMaKH();
            tmpMa = tmpMa.substring(tmpMa.indexOf('H') + 1);
            int tmpINT = Integer.parseInt(tmpMa);
            String MaKhachHang;
            if (tmpINT < 10) {
                MaKhachHang = IDTMP + "00" + (tmpINT + 1);
            } else if (tmpINT < 100) {
                MaKhachHang = IDTMP + "0" + (tmpINT + 1);
            } else {
                MaKhachHang = IDTMP + (tmpINT + 1);
            }
            String Ho = TextHo.getText();
            String Ten = TextTen.getText();
            String sdt = TextSDT.getText();
            String address = TextAddress.getText();
            String birth = TextBirth.getText();
            khdto = new KhachHangDTO(MaKhachHang, Ho, Ten, getItem, birth, address, sdt);

        }
        khbs.add(khdto);
        ShowModel(model, khbs.getList());
    }//GEN-LAST:event_btnAddActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        String MaKhachHang = TextMa.getText();
        String HoKhachHang = TextHo.getText();

        String TenKhacHang = TextTen.getText();
        String Address = TextAddress.getText();
        String Birth = TextBirth.getText();
        String SDT = TextSDT.getText();
        KhachHangDTO tmp = new KhachHangDTO(MaKhachHang, HoKhachHang, TenKhacHang, getItem, Birth, Address, SDT);

        khbs.set(tmp);
        ShowModel(model, khbs.getList());
    }//GEN-LAST:event_BtnEditActionPerformed

    private void TextAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAddressActionPerformed

    private void ComboxGenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboxGenderItemStateChanged
        getItem = (String) ComboxGender.getModel().getSelectedItem();
        System.out.println(getItem);
    }//GEN-LAST:event_ComboxGenderItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ShowModel(model, khbs.getList());
    }//GEN-LAST:event_jButton1ActionPerformed

    private ArrayList<KhachHangDTO> Search(String SearchString, ArrayList<KhachHangDTO> data) {
        String DateFrom = TextYearFrom.getText();
        String DateTo = TextYearTo.getText();
        String filterString = SearchString;
        ArrayList<KhachHangDTO> dsarr = new ArrayList<KhachHangDTO>();
        ArrayList<KhachHangDTO> dsarr1 = new ArrayList<KhachHangDTO>();
        ArrayList<KhachHangDTO> dsarr2 = new ArrayList<KhachHangDTO>();


        if (getItemFilter == null) {
            System.out.println("search bth");
            for (KhachHangDTO i : data) {
                if (!SearchString.equals("")) {
                    if (i.getHoKH().toLowerCase().indexOf(SearchString.toLowerCase()) != -1 || i.getTenKH().toLowerCase().indexOf(SearchString.toLowerCase()) != -1) {

                        dsarr.add(i);
                    }
                }

            }
        } else {
            System.out.println("search nang cao");
            for (KhachHangDTO i : data) {
                if (i.getHoKH().toLowerCase().indexOf(SearchString.toLowerCase()) != -1 || i.getTenKH().toLowerCase().indexOf(SearchString.toLowerCase()) != -1) {
                    if (i.getGioiTinh().equals(getItemFilter) && getItemFilter != null) {
                        dsarr.add(i);
                    }
                }
            }
        }
        if (!TextYearFrom.getText().equals("")) {
            System.out.println("Dau Nam");

            int getYearInput = Integer.parseInt(TextYearFrom.getText());
            if (dsarr.size() > 0) {
                for (KhachHangDTO i : dsarr) {
                    String year = i.getBirth();
                    year = year.substring(0, year.indexOf('-'));
                    int getyear = Integer.parseInt(year);
                    if (getYearInput <= getyear) {
                        dsarr1.add(i);
                        System.out.println(getyear + "\n");
                    }
                }

                dsarr = dsarr1;
                
            } else {
                for (KhachHangDTO i : data) {
                    String year = i.getBirth();
                    year = year.substring(0, year.indexOf('-'));
                    int getyear = Integer.parseInt(year);
                    if (getYearInput <= getyear) {
                        dsarr.add(i);
                        System.out.println(getyear + "\n");
                    }
                }
            }

        }

        if (!TextYearTo.getText().equals("")) {
            System.out.println("Cuoi Nam");
            int getYearInput = Integer.parseInt(TextYearTo.getText());
            if (dsarr.size() > 0) {
                for (KhachHangDTO i : dsarr) {
                    String year = i.getBirth();
                    year = year.substring(0, year.indexOf('-'));
                    int getyear = Integer.parseInt(year);
                    if (getYearInput >= getyear) {
                        System.out.println(getyear + "\n");
                        dsarr2.add(i);
                    }
                }
                dsarr = dsarr2;
            } else {

                for (KhachHangDTO i : data) {
                    String year = i.getBirth();
                    year = year.substring(0, year.indexOf('-'));
                    int getyear = Integer.parseInt(year);
                    if (getYearInput >= getyear) {
                        System.out.println(getyear + "\n");
                        dsarr.add(i);
                    }
                }
            }

        }
        return dsarr;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KhachHangGUI().setVisible(true);
//            }
//        });
//    }

    public void ShowModel(DefaultTableModel md, ArrayList<KhachHangDTO> dsdtp) {
        Vector data;
        model.setRowCount(0);
        for (KhachHangDTO n : dsdtp) {

            data = new Vector();
            data.add(n.getMaKH());
            data.add(n.getHoKH());
            data.add(n.getTenKH());
            data.add(n.getGioiTinh());
            data.add(n.getBirth());
            data.add(n.getAddress());
            data.add(n.getSDT());
            md.addRow(data);
        }
        tbl.setModel(md);
    }

    public void list() {
        if (khbs.getList() == null) {
            khbs.list();
        }
        ArrayList<KhachHangDTO> dsdto = khbs.getList();
        ShowModel(model, dsdto);

    }

    private void GetYearComboBox() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnEdit1;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JComboBox<String> ComboFilter;
    private javax.swing.JComboBox<String> ComboxGender;
    private javax.swing.JTextField TextAddress;
    private javax.swing.JTextField TextBirth;
    private javax.swing.JTextField TextFliter;
    private javax.swing.JTextField TextHo;
    private javax.swing.JTextField TextMa;
    private javax.swing.JTextField TextSDT;
    private javax.swing.JTextField TextTen;
    private javax.swing.JTextField TextYearFrom;
    private javax.swing.JTextField TextYearTo;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private KhachHangDTO KhachHangDTO(String text, String text0, String text1, String item, String text2) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
